//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public string CustomerID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string Address { get; set; }
        public string MaritalStatus { get; set; }
        public string Email { get; set; }
        public string Hobbies { get; set; }
        public string Likes { get; set; }
        public string Cuisines { get; set; }
        public string Sports { get; set; }
        public string Image { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
