//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalDetail
    {
        public string CustomerID { get; set; }
        public string Qualification { get; set; }
        public string School { get; set; }
        public string College { get; set; }
        public string Workstatus { get; set; }
        public string Organization_ { get; set; }
        public string Designation { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
